
genz <- c(
  "Yo, this is straight-up sick. ",
  "You crushed it with this one. ",
  "This shot goes hard. ",
  "Man, you’re out here killing it. ",
  "This is straight fire, no cap. ",
  "The detail here is wild. ",
  "How do you even do this? ",
  "This is next-level stuff, for real. ",
  "You snapped with this. ",
  "This is clean as hell. ",
  "This pic hits different. ",
  "Straight heat, no doubt. ",
  "Not gonna lie, this is unreal. ",
  "You’re built different, for real. ",
  "This is a banger, no question. ",
  "This shot’s got some crazy vibes. ",
  "The talent here is insane. ",
  "This is legendary, no doubt. ",
  "You just leveled up with this one. ",
  "This is so raw, man. ",
  "This is a flex. ",
  "This one’s an instant classic. ",
  "This is legit insane. ",
  "You’ve got an eye for this. ",
  "Not even gonna lie, this is dope. ",
  "This shot’s got some serious energy. ",
  "This is top-tier. ",
  "Man, you’re a wizard with the camera. ",
  "This is some pro-level stuff. ",
  "You’re on another level with this one. ",
  "This is just too good. ",
  "This is so crisp. ",
  "This is the kind of shot people remember. ",
  "You’re straight-up unstoppable. ",
  "This is art. ",
  "You’ve outdone yourself here. ",
  "This is peak content. ",
  "This photo is carrying serious weight. ",
  "You’re setting the standard with this one. "
)

bronobro <- c(
  "This slaps, for real! ",
  "The vibes are immaculate. ",
  "You understood the assignment. ",
  "This shot is straight-up fire. ",
  "Lowkey obsessed with this. ",
  "This is next-level. ",
  "Can’t stop staring at this. ",
  "This is giving main character energy. ",
  "Too good, I’m shook. ",
  "This pic is a whole mood. ",
  "The aesthetic is on point. ",
  "Big flex with this one. ",
  "This is a certified banger. ",
  "The creativity here is unreal. ",
  "I’m losing it over this. ",
  "This deserves all the hype. ",
  "This is GOAT-level content. ",
  "The drip in this photo is insane. ",
  "I’m screaming, this is so good. ",
  "Straight chef’s kiss. ",
  "Tell me why this is so iconic. ",
  "This just ate and left no crumbs. ",
  "You’re really out here making magic. ",
  "No thoughts, just this masterpiece. ",
  "This is peak aesthetic. ",
  "Literally can’t handle how good this is. ",
  "This is giving everything it needs to give. ",
  "Ugh, the talent jumped out. ",
  "This is unreal, I’m obsessed. ",
  "Photo dump goals right here. ",
  "This is pure serotonin. ",
  "Not me saving this for inspo. ",
  "You’re out here breaking the internet. ",
  "This is an absolute slay. ",
  "This shot is elite. ",
  "IDK how you do it, but keep doing it. "
)

boomer <- c(
  "This is absolutely wonderful.  ",
  "What a beautiful picture.  ",
  "You’ve really outdone yourself this time.  ",
  "This reminds me of the good old days.  ",
  "So picturesque, great job!  ",
  "How did you manage to capture this?  ",
  "You have such a natural talent.  ",
  "This photo tells a whole story.  ",
  "It’s just like a postcard.  ",
  "Simply breathtaking work.  ",
  "Keep up the excellent work!  ",
  "I could frame this and put it on my wall.  ",
  "This makes me want to get outside more.  ",
  "They don’t make moments like this anymore.  ",
  "What a sharp and clear photo.  ",
  "This should be in a magazine.  ",
  "You’ve got an eye for detail, no doubt about it.  ",
  "This brings back so many memories.  ",
  "Can’t believe how talented you are!  ",
  "Wow, what a masterpiece.  "
)

victorian <- c(
  "This image is most splendid indeed.  ",
  "Pray, how dost thou create such magnificence?  ",
  "A truly breathtaking composition, dear sir or madam.  ",
  "This scene doth transport one to another realm.  ",
  "I am utterly enamoured by this work of art.  ",
  "Thy skills behind the lens are unparalleled.  ",
  "This doth evoke a profound sense of wonderment.  ",
  "The beauty captured herein is most divine.  ",
  "This is a vision of paradise, is it not?  ",
  "Thou art a true master of thine craft.  ",
  "This photograph is worthy of the highest accolades.  ",
  "I am quite astonished by the perfection of this image.  ",
  "What a most enchanting view thou hast captured.  ",
  "Surely, this is a gift from the heavens themselves.  ",
  "Every detail here is a marvel to behold.  ",
  "I find myself lost in the beauty of this scene.  ",
  "This creation is a veritable masterpiece.  ",
  "How doth one achieve such artistic brilliance?  ",
  "Thy work is as timeless as it is exquisite.  ",
  "This photograph shall linger in my thoughts for days to come.  ",
  "Methinks this image doth capture the soul of the moment.  ",
  "What a most divine tapestry of light and shadow.  ",
  "The elegance of this piece doth leave me speechless.  ",
  "Surely thou art inspired by the muses themselves.  ",
  "This is a most wondrous feast for the eyes.  ",
  "Thy photograph doth remind one of the works of the great masters.  ",
  "It is as though the very essence of nature is contained within.  ",
  "Such majesty as this is seldom seen in our age.  ",
  "My heart is warmed by the serenity of this image.  ",
  "This art is so fine it could adorn the walls of a great hall.  ",
  "Never have I beheld such a scene so beautifully rendered.  ",
  "The craftsmanship displayed here is beyond compare.  ",
  "Thy artistry doth surpass all expectation.  ",
  "I am in awe of the splendour thou hast captured.  ",
  "Each element within this frame is perfectly placed.  ",
  "This doth bring great joy to mine eyes and spirit.  ",
  "I am compelled to sing praises of thine exceptional talent.  ",
  "Thou hast made the ordinary appear most extraordinary.  ",
  "A true marvel, worthy of admiration and acclaim.  "
)

bloodborne <- c(
  "Behold, a sight most wondrous.  ",
  "What dark artistry lies behind this creation?  ",
  "This image stirs a strange and eldritch beauty.  ",
  "Thine eye for detail is a hunter's blessing.  ",
  "The composition is as haunting as it is sublime.  ",
  "A work both beautiful and terrible to behold.  ",
  "This vision echoes with forgotten truths.  ",
  "Such grandeur is scarcely of this world.  ",
  "A masterpiece borne of light and shadow.  ",
  "This scene could only be conjured by one touched by the Great Ones.  ",
  "Do not avert thine eyes from this dreadful majesty.  ",
  "The craftsmanship here doth rival that of Byrgenwerth.  ",
  "A fleeting glimpse of the cosmos, captured for eternity.  ",
  "This frame hums with an otherworldly resonance.  ",
  "Thou hast woven beauty and horror into one.  ",
  "The eldritch whispers grow louder as I gaze upon this.  ",
  "The light hath a sinister charm, doth it not?  ",
  "This image is a testament to the hunter's will.  ",
  "Even the pale moon would envy such a sight.  ",
  "Aye, there is wisdom in thine artistry, but also madness.  ",
  "This image shall linger in the depths of my dreams.  ",
  "Thy work evokes both awe and a quiet terror.  ",
  "A vision fit for the Chapel of the Good Blood.  ",
  "How doth one create such a tapestry of shadow and light?  ",
  "This scene is steeped in the allure of the forbidden.  ",
  "I sense the whispers of the Great Ones within this frame.  ",
  "The air itself grows heavy in the presence of such beauty.  ",
  "A foreboding stillness pervades this image.  ",
  "Surely this is the work of a hunter of rare skill.  ",
  "This doth evoke the cold brilliance of the moonlit night.  ",
  "A true hunter sees beauty even in the grotesque.  ",
  "The frame speaks of secrets best left unknown.  ",
  "What celestial truths hast thou captured here?  ",
  "This vision hath awakened something deep within me.  ",
  "A fine work, touched by both brilliance and the abyss.  ",
  "Even the blood would stir at such a sight.  ",
  "Such beauty is but a fleeting gift in a cruel world.  ",
  "This is no mere photograph; it is a glimpse into the void.  ",
  "A haunting masterpiece, wrought with care and dread.  "
)

lovecraft <- c(
  "Behold, a vision that transcends mortal comprehension.  ",
  "This image stirs echoes of unspeakable realms.  ",
  "What eldritch force guided thine hand to craft this?  ",
  "A beauty both maddening and ineffable lies herein.  ",
  "This scene whispers of things best left unseen.  ",
  "I dare not gaze too long, lest my mind unravel.  ",
  "Such artistry seems touched by the tendrils of the unknown.  ",
  "The light doth emanate with a dread cosmic resonance.  ",
  "This image is a portal to realms beyond human understanding.  ",
  "What ancient and unknowable truths are captured here?  ",
  "This work is suffused with a terror that defies words.  ",
  "I feel the gaze of forgotten gods upon this frame.  ",
  "There is a nameless dread lurking within this beauty.  ",
  "This photograph doth hum with an otherworldly power.  ",
  "Surely, this is the work of one who hath glimpsed the abyss.  ",
  "The geometry of this frame is... wrong, yet compelling.  ",
  "This vision is both a blessing and a curse to behold.  ",
  "Such imagery is the stuff of fevered dreams and nightmares.  ",
  "It is as though the stars themselves conspired to create this.  ",
  "The composition whispers of cyclopean halls and ancient cities.  ",
  "One cannot deny the shadow of the great and terrible unknown here.  ",
  "This work is an invocation of the ineffable.  ",
  "The light and shadow form a pattern that defies mortal reason.  ",
  "A fragment of some eldritch truth is captured in this frame.  ",
  "I sense the presence of vast and uncaring cosmic forces here.  ",
  "This image teeters on the brink of sanity and madness.  ",
  "A vision so profound, it seems torn from the dreams of the ancients.  ",
  "What mind could conjure such an unearthly creation?  ",
  "This frame stirs memories of things I have never known.  ",
  "The horror and beauty here are inextricably entwined.  ",
  "One cannot look upon this and remain unchanged.  ",
  "This work doth reverberate with the echoes of forgotten aeons.  ",
  "An image touched by the infinite void beyond the stars.  ",
  "There is a cold and distant intelligence behind this scene.  ",
  "This vision awakens a deep and primal fear.  ",
  "Surely, this is a glimpse into the maddening truth of existence.  ",
  "The very fabric of reality seems to shift around this image.  ",
  "This photograph is an invocation to forces we cannot comprehend.  ",
  "What eldritch whispers echo within this still frame?  ",
  "This is no mere art, but a shard of the unknowable.  "
)

hemingway <- c(
  "This is a good picture.  ",
  "You’ve captured something real here.  ",
  "It’s simple, but it works.  ",
  "There’s strength in this shot.  ",
  "I like how it feels.  ",
  "It says more than words could.  ",
  "This one hits.  ",
  "There’s beauty in the quiet.  ",
  "It’s not loud, but it’s powerful.  ",
  "You’ve found something honest here.  ",
  "It’s calm, but there’s a story.  ",
  "You’ve caught the light just right.  ",
  "This is how it should be.  ",
  "You know what you’re doing.  ",
  "There’s a lot in this picture, even if it’s not obvious.  ",
  "It’s a good, clean shot.  ",
  "This one stays with you.  ",
  "It’s the kind of photo that makes you think.  ",
  "You’ve made something real.  ",
  "There’s a truth in this image.  ",
  "It’s beautiful in its quiet way.  ",
  "It doesn’t try too hard.  ",
  "This shot tells the story without shouting.  ",
  "I could look at this for a long time.  ",
  "It’s a fine capture of the moment.  ",
  "There’s a stillness here that I like.  ",
  "This is the kind of image that lasts.  ",
  "It’s powerful in its simplicity.  ",
  "There’s nothing wasted here.  ",
  "You’ve found something worth seeing.  ",
  "This photo holds up.  ",
  "It’s clean. It’s real. It’s good.  "
)

epic <- c(
  "Lo! A vision of great splendor, worthy of the gods themselves.  ",
  "Behold the frame, where light and shadow clash like titans!  ",
  "O, noble work, a testament to thine artistry that outshines the stars!  ",
  "A scene of beauty, as if drawn by the hand of Athena herself.  ",
  "Mighty is the hand that captured such a vision—truly, a hero’s feat!  ",
  "Like the sweeping tides of the Aegean, this image doth stir the soul.  ",
  "Thine eye hath pierced the veil of time, bringing forth this ageless beauty.  ",
  "O wondrous sight! A glimpse into the heavens themselves, framed in light.  ",
  "This image, a song of glory, echoing across the halls of Olympus.  ",
  "By the will of Zeus, this work shall endure through the ages.  ",
  "Thy craft doth rival the works of Hephaestus, creator of the gods' finest armor.  ",
  "In this frame, the very spirit of adventure and grandeur is captured.  ",
  "A picture to stir the hearts of men, as the epic songs of old!  ",
  "Thine art is as eternal as the Iliad, a tale woven into the fabric of time.  ",
  "Behold, a treasure more precious than gold or the fruits of war.  ",
  "This image sings with the soul of the heroes of old, shining in glory.  ",
  "As Odysseus, brave and bold, crossed the seas, so too doth this frame conquer the heart.  ",
  "In this image, there is the strength of Achilles and the wisdom of Nestor.  ",
  "O fleeting moment, immortalized in a picture that shall endure forevermore.  ",
  "This scene, a testament to mortal skill, as glorious as the gods' own works.  ",
  "A vision of such beauty, it echoes through the ages like the winds of Troy.  ",
  "What fate has brought such a masterpiece forth from the hands of men?  ",
  "A triumph worthy of the greatest bards, who sang of valor and glory!  ",
  "The light within this image shines like the golden helm of Agamemnon.  ",
  "A frame that shall endure as long as the tales of old, sung by a thousand voices.  ",
  "O noble image! Thou art a work fit for the halls of Valhalla itself.  ",
  "This sight stirs the heart like the roar of battle upon the sands of Ilium.  ",
  "As the gods watch over this creation, so too will it stand the test of time.  ",
  "In thee, O image, is the weight of legends and the whispers of heroes.  "
)

norse <- c(
  "A vision forged in the fires of strength and resilience.  ",
  "This frame stands as tall and steadfast as the ancient world tree.  ",
  "In this moment, I see the clash of thunder and the stillness of the void.  ",
  "A sight as eternal as the mountains that pierce the sky.  ",
  "The light here burns with the power of untamed storms.  ",
  "This image captures the pulse of a world that never yields.  ",
  "Like the roots of the great tree, this picture connects all things.  ",
  "This frame carries the might of those who rise against fate itself.  ",
  "In this work, I see the forging of something that will endure through ages.  ",
  "A scene of power, as vast as the horizon itself.  ",
  "There is a force in this image that commands the elements to bend.  ",
  "This picture holds the weight of ancient wisdom and boundless strength.  ",
  "The light in this photograph strikes with the precision of a warrior's aim.  ",
  "This image calls to mind the echo of distant winds, untouched by time.  ",
  "The strength captured here is unyielding, like the stone and the sky.  ",
  "A creation as untamable as the wild forces that shape the world.  ",
  "This scene stands as a testament to the untold power of nature itself.  ",
  "In this work, I see the quiet before a storm—a stillness that holds power.  ",
  "This frame captures the rhythm of a world that has known battle and peace.  ",
  "What is captured here is as old as time itself, enduring and constant.  ",
  "The very essence of nature pulses within this photograph.  ",
  "This image is a glimpse into the forces that shape the world, seen in a single moment.  ",
  "A moment of brilliance that stands defiant against the ravages of time.  ",
  "This scene feels like it was carved by the very hands that shaped the earth.  ",
  "The shadows and light dance like ancient forces at work.  ",
  "There is a depth here, as endless as the realms that stretch beyond sight.  ",
  "This image tells a story of resilience and untold power, captured in stillness.  ",
  "What is seen here is timeless, woven into the fabric of the world itself.  "
)



classics <-c("Amazing shot! ", "This is awsome ", "I really like this ", "Really cool ",
            "I really like your style " , "This is crazy cool! ",
            "Great work! ", "This is so cool! ", "Good job fam ", "Keep it coming ", "So nice! ",
            "Literally breathtaking! ", "Soooo cool!! ", "I like it! ", "More of this ",
            "This is loco! Nice one ", "Awsome style ", "Daaaamn! ", "Awsome capture!! ",
            "Sehr cool ", "You done did it again, real nice! ", "really cool capturee ",
            "i love thiiis ", "Niceee job ", "You never fail to deliver! ", "Like like likee! ",
            "Wunderschööön ", "Sieht mega aus! ", "cool perspective ", "Great stuff! Keep it coming ",
            "great work!! ", "nice pic! ", "You have an outstanding style ", "Outstanding! ",
            "Taking notes! Awsome capture ", "Sehr schön! ")

jis<- c("🔥", "❤️", "💛", "📷", "📸", "💥", "💪", "🙌",
        "👏", "😍", "🤩", "😻", "💯", "🔥", "🔥", "🔥", 
        "✍️")